### ISSUE TITLE
Zero tolerance causes: UnhandledPromiseRejectionWarning: TypeError: this.resolveImagePathRelativeFromReport is not a function

### ISSUE THREAD

**Issue by mirao** [Percona-Lab/codeceptjs-resemblehelper#102]
It seems to be a regression in 1.9.5
It works well for me with 1.9.4

Run test with this step
```js
I.seeVisualDiff(image, { prepareBaseImage: false, tolerance: 0 });
```
**Expected result:**

- No issue

**Actual result:**

- Test passes, but an exception is logged:
```
I see visual diff "DND_Editor_Default_Position_chrome.png", {"prepareBaseImage":false,"tolerance":0}
      › Tolerance Level Provided 0
      › Diff Image File Saved to: /home/mirao/workspace/codeceptjs/tests/spork-publisher/home/mirao/workspace/codeceptjs/tests/spork-publisher/screenshots/diff/Diff_DND_Editor_Default_Position_chrome.png
      › MisMatch Percentage Calculated is 0.00 for baseline DND_Editor_Default_Position_chrome.png
(node:806286) UnhandledPromiseRejectionWarning: TypeError: this.resolveImagePathRelativeFromReport is not a function
    at ResembleHelper._addMochaContext (/home/mirao/workspace/codeceptjs/node_modules/codeceptjs-resemblehelper/index.js:194:46)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:806286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:806286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Workaround:**

- Use a non zero tolerance, e.g. `{ tolerance: 0.01 }`

**Used SW:**

- Node v14.18.1
- CodeceptJS 3.0.7
- codeceptjs-resemblehelper 1.9.5

**Comment by puneet0191** [comment]
thanks a lot for reporting this.

**Comment by armandsz22** [comment]
Same issue.

**Comment by puneet0191** [comment]
@armandsz22 @mirao anyone has time to send a PR to fix this?

**Comment by mirao** [comment]
@puneet0191 PR: https://github.com/codeceptjs/codeceptjs-resemblehelper/pull/119
